Repository kocdigital/Carbon, pull requests merged in 2022-12, with the labels that each got.

#57 [Carbon.MassTransit] Quorum Queues introduced
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
  Carbon.MassTransit/ReceiveEndpointObserver.cs
Labels: enhancement

#58 Documentation added for cassandra packages
  .gitignore
  Carbon Framework.sln
  Carbon.Cassandra.Abstractions/README.md
  Carbon.Cassandra/README.md
  Carbon.WebApplication.SolutionService/NuGet.Config
  SolutionItems/NuGet.Config
Labels: documentation

#59 Documentation added for Common and Console Packages
  Carbon.Common/README.md
  Carbon.ConsoleApplication.Extensions/README.md
Labels: documentation

#60 Documentation added for Domain Packages
  Carbon.Domain.Abstractions/README.md
  Carbon.Domain.EntityFrameworkCore.Extensions/README.md
Labels: documentation

#61 Documentation for ElasticSearch packages added
  Carbon.ElasticSearch.Abstractions/README.md
  Carbon.ElasticSearch/README.md
Labels: documentation

#64 Npgsql datetime conversion approach announced as dotnet 6 breaking change defered to a later time, overriding with a AppContext switch to continue using default behaviour
  Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
  Carbon.WebApplication.EntityFrameworkCore/IApplicationBuilderExtensions.cs
Labels: quick fix

#65 Quick fix for optional legacy behaviour
  Carbon.WebApplication.EntityFrameworkCore/Carbon.WebApplication.EntityFrameworkCore.csproj
  Carbon.WebApplication.EntityFrameworkCore/IApplicationBuilderExtensions.cs
Labels: quick add, quick fix

#67 Enabling pub/sub is now optional, defaults to false
  Carbon.Redis/Abstractions/ICarbonCacheExtensions.cs
  Carbon.Redis/Carbon.Redis.csproj
  Carbon.Redis/Extensions/CarbonRedisCache.cs
  Carbon.Redis/Extensions/CarbonRedisCacheOptions.cs
  Carbon.Redis/Extensions/ICarbonRedisBuilderExtensions.cs
  Carbon.Redis/README.md
Labels: bug, enhancement

#68 User added to redis settings
  Carbon.Redis/Carbon.Redis.csproj
  Carbon.Redis/RedisSettings.cs
  Carbon.Redis/ServiceCollectionExtensions.cs
Labels: quick add

#72 Fixed a bug for quorum ReqRespAsync patterns
  Carbon.MassTransit/AsyncReqResp/RequestHandlerActivity.cs
  Carbon.MassTransit/AsyncReqResp/ResponseHandlerActivity.cs
  Carbon.MassTransit/Carbon.MassTransit.csproj
Labels: bug, quick fix

#79 Fixed a critical bug when ReqRespAsync is used in multiple APIs and same virtual hosts
  Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
Labels: bug, quick fix

#81 ReqRespAsync another fix
  Carbon.MassTransit/AsyncReqResp/Events/IRequestCarrierRequest.cs
  Carbon.MassTransit/AsyncReqResp/Events/RequestCarrierRequest.cs
  Carbon.MassTransit/AsyncReqResp/RequestHandlerActivity.cs
  Carbon.MassTransit/AsyncReqResp/StaticHelpers.cs
  Carbon.MassTransit/Carbon.MassTransit.csproj
Labels: bug, quick fix

#82 Multiple Responder for ReqRespAsync
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
  Carbon.MassTransit/README.md
Labels: enhancement, quick add

#86 Quick Fix
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
Labels: bug, quick fix

#87 Quick Fix
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
  Carbon.MassTransit/README.md
  Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
Labels: quick fix

#88 MultiTarget framework support (.net3.1 - 5 - 6) (MassTransit and dependent projects)
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.WebApplication.SolutionService/Carbon.WebApplication.SolutionService.csproj
Labels: enhancement

#90 Fixes #89
  Carbon.MassTransit/Carbon.MassTransit.csproj
  Carbon.MassTransit/IServiceCollectionConfiguratorExtensions.cs
Labels: bug, quick fix
